---
title: "Lab Alumni"
---

Dr. Mathew Barber, PhD 2011 — Current Position: Postdoctoral Scholar, Elde Lab, University of Utah

Dr. Olivier Binda, Post-Doc 2009 — Current Position: Lecturer, Newcastle University, England

Dr. Dennis Bua, PhD 2012 — Current Position: Staff Scientist, Fraser Lab, Stanford, CA, USA

Shuai Chen, Masters 2011 — Current Position: Executive Director SCRAP

Dr. Peggie Cheung, PhD 2012 — Current Position: Postdoctoral Scholar, Utz Lab, Stanford, CA USA

Dr. Erin Green, Post-Doc 2013 — Current Position: Assistant Professor, University of Maryland, Baltimore, MD, USA

Dr. Ioulia Kachirskaia, PhD 2008 — Current Position: Innovation Consultant, Kaiser Care Management Institute

Dr. Alex Kuo, PhD 2011 — Current Position: Postdoctoral Scholar, Utz Lab, Stanford, CA USA

Dr. Dan Levy, Post-Doc 2012 — Current Position: Assistant Professor, Faculty of Health Sciences, Ben Gurion University of the Negev, Israel

Dr. Gloria Mas Martin, Post-Doc 2013 — Current Position: Research Scientist, CRG – Centre de Regulació Genòmica, Barcelona Spain

Dr. Yoichi Munehira, Visiting Scholar 2014-2016 — Current Position: Researcher, Daiichi Sankyo Co, Shinagawa, Tokyo, Japan

Dr. Kaitlyn Coil Moore, PhD 2014 — Current Position:  Scientist, ArcherDX, Inc., Boulder, CO, USA

Rick van Nuland, Post-Doc 2017 — Current Position: Program Manager Life Science at Lygature, Utrecht, The Netherlands

Dr. Nicolas Reynoird, Post-Doc 2014 — Current Position:  Researcher CNRS at the Institute for Advanced Biosciences (INSERM – CNRS – Université Grenoble Alpes), France

Dr. Xiaobing Shi, Post-Doc 2008 — Current Position: Associate Professor, Dept. of Biochemistry, MD Anderson, TX, USA

Dr. Lisandra West, PhD 2011 — Current Position: Assistant Editor CollabRx