---
title: "Publications"
---

For latest updates on the lab's recent papers and citation information, please see the comprehensive [Google Scholar Citations page](https://scholar.google.com/citations?user=jopHD6kAAAAJ&hl=en).

**2020:**

- Shaobo Dai, John R. Horton, Alex W. Wilkinson, Or Gozani, Xing Zhang and Xiaodong Cheng (2020) An engineered variant of SETD3 methyltransferase alters target specificity from histidine to lysine methylation. <a href="https://www.jbc.org/content/early/2020/01/07/jbc.RA119.012319.short" target="_blank"> <strong> <span style="color: #0000ff;"> Journal of Biological Chemistry. </span></strong></a> 2020, doi: 10.1074/jbc.RA119.012319  PMID: 31911441

**2019:**

- Bohdan B. Khomtchouk\*, Diem-Trang Tran\*, Kasra A. Vand, Matthew Might, Or Gozani and Themistocles L. Assimes (2019) Cardioinformatics: the nexus of bioinformatics and precision cardiology. <a href="https://academic.oup.com/bib/advance-article-abstract/doi/10.1093/bib/bbz119/5626336?redirectedFrom=fulltext" target="_blank"> <strong> <span style="color: #0000ff;"> Briefings in Bioinformatics. </span></strong></a> 2019, doi: 10.1093/bib/bbz119  PMID: 31802103
\*These Authors Contributed Equally

- Bohdan B. Khomtchouk, Kasra A. Vand\*, William C. Koehler\*, Diem-Trang Tran, Kai Middlebrook,  Shyam Sudhakaran, Christopher S. Nelson, Or Gozani and Themistocles L. Assimes (2019) HeartBioPortal: An Internet-of-Omics for Human Cardiovascular Disease Data. <a href="https://www.ahajournals.org/doi/10.1161/CIRCGEN.118.002426" target="_blank"> <strong> <span style="color: #0000ff;"> Circulation: Genomic and Precision Medicine. </span></strong></a> 2019 Ap;12(4):e002426. doi: 10.1161/CIRCGEN.118.002426  PMID: 31294639
\*These Authors Contributed Equally

- Dai S, Horton JR, Woodcock CB, Wilkinson AW, Zhang X, Gozani O and X Cheng (2019) Structural basis for the target specificity of actin histidine methyltransferase SETD3. <a href="https://www.nature.com/articles/s41467-019-11554-6" target="_blank"> <strong> <span style="color: #0000ff;"> Nature Communications. </span></strong></a> 2019 Aug 6;10(1):3541 PMID: 31388018

- Jonathan Diep\*, Yaw Shin Ooi\*, Alex W. Wilkinson\*, Christine E. Peters, Eileen Foy, Jeffrey R. Johnson, James Zengel, Siyuan Ding, Kuo-Feng Weng, Orly Laufman, Gwendolyn Jang, Tracy Young, Erik Verschüren, Kristi Kobluk, Peter Sarnow, Harry B. Greenberg, Ruth Hüttenhain, Claude M. Nagamine, Raul Andino\#,  Nevan J. Krogan\#, Or Gozani\#, Jan E. Carette\# (2019) Enterovirus Pathogenesis Requires the Host Methyltransferase SETD3. <a href="https://www.nature.com/articles/s41564-019-0551-1" target="_blank"> <strong> <span style="color: #0000ff;"> Nature Microbiology </span></strong></a>, Sept 16; 10.10138/s441564-019-0551-1  PMID: 31527793
\*These Authors Contributed Equally; \# Co-correspondence 

- Tie-Mei Li\*, John P. Coan\*, Krzysztof Krajewski, Lichao Zhang, Joshua E. Elias, Brian D. Strahl, Or Gozani\# and Katrin F. Chua\#. Binding to medium and long chain fatty acyls is a common property of HEAT and ARM repeat modules (2019). <a href="https://www.nature.com/articles/s41598-019-50817-6" target="_blank"> <strong> <span style="color: #0000ff;"> Scientific Reports </span></strong></a> Oct 2;9(1):14226. PMID 315784817
\*These Authors Contributed Equally; \# Co-correspondence 

- Dylan Husmann and Or Gozani. Histone lysine methyltransferases in biology and disease (2019). <a href="https://www.nature.com/articles/s41594-019-0298-7" target="_blank"> <strong> <span style="color: #0000ff;"> Nature Structural and Molecular Biology </span></strong></a> 2019 Oct; 26(10):880-889; PMID 31582846

**2018:**

- Alex W. Wilkinson\*, Jonathan Diep\*, Shaobo Dai\*, Shuo Liu, Yaw Shin Ooi,  Dan Song, Tie-Mei Li, John R. Horton, Xing Zhang, Chao Liu, Darshan V. Trivedi, Katherine M. Ruppel, José G. Vilches-Moure,  Kerriann M. Casey, Justin Mak, Tina Cowan, Joshua E. Elias, Claude M. Nagamine, James A. Spudich, Xiaodong Cheng\#, Jan E. Carette\# and Or Gozani\# (2018) SETD3 is an Actin Histidine Methyltransferase that Prevents Primary Dystocia. <a href="https://www.nature.com/articles/s41586-018-0821-8" target="_blank"> <strong> <span style="color: #0000ff;"> Nature. </span></strong></a> 10.1038/s41586-018-0821-8. (Advance Online Publication)
\*These Authors Contributed Equally; \# Co-correspondence 

- Shuo Liu\*, Simone Hausmann\*, Scott Moore Carlson, Mary Esmeralda Fuentes, Joel William Francis, Renjitha Pillai, Shane Michael Lofgren, Laura Hulea, Kristofferson Tandoc, Jiuwei Lu, Ami Li, Nicholas Dang Nguyen, Marcello Caporicci, Michael Paul Kim, Anirban Maitra, Huamin Wang, Ignacio Ivan Wistuba, John Anthony Porco, Jr., Michael Cory Bassik, Joshua Eric Elias, Jikui Song, Ivan Topisirovic, Capucine Van Rechem, Pawel Karol Mazur\# and Or Gozani\# (2018) METTL13 methylation of eEF1A increases translational output to promote tumorigenesis. <a href="https://www.cell.com/cell/fulltext/S0092-8674(18)31563-0?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867418315630%3Fshowall%3Dtrue" target="_blank"> <strong> <span style="color: #0000ff;"> Cell. </span></strong></a>
\*These Authors Contributed Equally; \# Co-correspondence

**2017:**

- Sankaran SM, Gozani O. (2017) Characterization of H3.3K36M as a tool to study H3K36 methylation in cancer cells. <a href="https://www.ncbi.nlm.nih.gov/pubmed/28933651" target="_blank"><strong><span style="color: #0000ff;"> Epigenetics. </span></strong></a> 2017;12(11):917-922. doi: 10.1080/15592294.2017.1377870  PMID: 28933651

- Kutateladze TG, Gozani O, Bienz M, Ostankovitch M. (2017) Histone modifications for chromatin dynamics and cellular plasticity. <a href="https://www.ncbi.nlm.nih.gov/pubmed/?term=28623961" target="_blank"><strong><span style="color: #0000ff;"> J Mol Biol. </span></strong></a> 2017 Jun 30;429(13):1921-1923. doi: 10.1016/j.jmb.2017.06.001  PMID: 28623961

- Carlson SM, Soulette CM, Yang Z, Elias JE, Brooks AN, Gozani O. (2017) RBM25 is a global splicing factor promoting inclusion of alternatively spliced exons and is itself regulated by lysine mono-methylation. <a href="https://www.ncbi.nlm.nih.gov/pubmed/?term=28655759" target="_blank"><strong> <span style="color: #0000ff;"> J Biol Chem. </span></strong></a> 2017 Jun 27. pii: jbc.M117.784371. doi: 10.1074/jbc.M117.784371  PMID: 28655759

- Wilkinson AW, Gozani O. (2017) Cancer epigenetics: Reading the future of leukaemia. <a href="https://www.ncbi.nlm.nih.gov/pubmed/?term=28241142" target="_blank"> <strong> <span style="color: #0000ff;"> Nature. </span></strong></a> 2017 Mar 1. doi: 10.1038/nature21894. PMID: 28241142

**2016:**

- Carlson SM, Gozani O. (2016) Nonhistone Lysine Methylation in the Regulation of Cancer Pathways. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=27580749" target="_blank"><strong> <span style="color: #0000ff;"> Cold Spring Harb Perspect Med</span></strong></a>. 2016 Nov 1;6(11). pii: a026435. doi: 10.1101/cshperspect.a026435 PMID: 27580749

- Huang WH, Guenthner CJ, Xu J, Nguyen T, Schwarz LA, Wilkinson AW, Gozani O, Chang HY, Shamloo M, Luo L. (2016) Molecular and Neural Functions of Rai1, the Causal Gene for Smith-Magenis Syndrome. <a href="https://www.ncbi.nlm.nih.gov/pubmed/27693255" target="_blank"><strong> <span style="color: #0000ff;">Neuron</span></strong></a>. 2016 Oct 19;92(2):392-406. doi: 10.1016/j.neuron.2016.09.019.PMID: 27693255

- Munehira Y, Yang Z, Gozani O. (2016) Systematic Analysis of Known and Candidate Lysine Demethylases in the Regulation of Myoblast Differentiation. <a href="https://www.ncbi.nlm.nih.gov/pubmed/27732873" target="_blank"><strong> <span style="color: #0000ff;">J Mol Biol</span></strong></a>. 2016 Oct 11. pii: S0022-2836(16)30419-3. doi: 10.1016/j.jmb.2016.10.004. PMID: 27732873

- Zhu L, Li Q, Wong SH, Huang M, Klein BJ, Shen J, Ikenouye L, Onishi M, Schneidawind D, Buechele C, Hansen L, Duque-Afonso J, Zhu F, Mas Martin G, Gozani O, Majeti R, Kutateladze TG, Cleary ML.(2016) ASH1L links histone H3 lysine 36 di-methylation to MLL leukemia.<a href="http://cancerdiscovery.aacrjournals.org/content/early/2016/05/06/2159-8290.CD-16-0058.long" target="_blank"> <strong> <span style="color: #0000ff;">Cancer Discov</span></strong></a>. 2016 May 6. pii: CD-16-0058. PMID: 27154821

- Nicolas Reynoird*, Pawel K. Mazur*, Timo Stellfeld, Natasha M. Flores, Shane M. Lofgren, Scott M. Carlson, Elisabeth Brambilla, Pierre Hainaut, Ewa B. Kaznowska, Cheryl H. Arrowsmith, Purvesh Khatri, Carlo Stresemann, Or Gozani#, and Julien Sage# (2016) Coordination of stress signals by the lysine methyltransferase SMYD2 promotes pancreatic cancer. <a href="http://genesdev.cshlp.org/content/30/7/772.long" target="_blank"> <strong> <span style="color: #0000ff;"> Genes Dev </span></strong></a>. 2016 Apr 1;30(7):772-85. doi: 10.1101/gad.275529.115. PMID: 26988419 *These authors contributed equally to this work; #Equal correspondence

- Li S, Yang Z, Du X, Liu R, Wilkinson AW, Gozani O, Jacobsen SE, Patel DJ, Du J. (2016) Structural Basis for the Unique Multivalent Readout of Unmodified H3 Tail by Arabidopsis ORC1b BAH-PHD Cassette. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=26876097" target="_blank"> <strong> <span style="color: #0000ff;"> Structure </span></strong></a>. 2016 Mar 1;24(3):486-94. PMID: 26876097

- Sankaran SM, Wilkinson AW, Gozani O. (2016) A PWWP domain of histone-lysine N-methyltransferase NSD2 binds to dimethylated Lys36 of histone H3 and regulates NSD2 function at chromatin. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=26912663" target="_blank"><strong> <span style="color: #0000ff;"> J Biol Chem </span></strong></a>. 2016 Apr 15;291(16):8465-74. doi: 10.1074/jbc.M116.720748. PMID: 26912663

**2015:**

- van Nuland R, Gozani O. (2015) H4K20 methylation: expanding the signaling potential of the proteome one methyl moiety at a time. <a href="http://www.ncbi.nlm.nih.gov/pubmed/26598646" target="_blank"> <strong> <span style="color: #0000ff;"> Mol Cell Proteomics</span></strong></a>. 2015 Nov 23. pii: mcp.R115.054742 PMID: 26598646

- Shoudeng Chen#, Ze Yang#, Alex W. Wilkinson#, Aniruddha J. Deshpande, Simone Sidoli, Krzysztof Krajewski, Brian D. Strahl, Benjamin A. Garcia, Scott A. Armstrong, Dinshaw J. Patel# and Or Gozani# (2015) The PZP domain of AF10 senses unmodified H3K27 to regulate DOT1L-mediated methylation of H3K79. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Shoudeng+Chen%2C+Ze+Yang%2C+Alex+W.+Wilkinson%2C+Aniruddha+J.+Deshpande" target="_blank"><strong><span style="color: #0000ff;"> Molecular Cell </span></strong> </a>, PMID: 26439302 #These authors contributed equally to this work; #Equal correspondence

- Zhang W, Sankaran S, Gozani O, Song J. (2015) A Meier-Gorlin syndrome mutation impairs the ORC1-nucleosome association. <a href="http://www.ncbi.nlm.nih.gov/pubmed/25689043" target="_blank"><strong><span style="color: #0000ff;"> ACS Chem Biol</span></strong></a>. 2015 May 15;10(5):1176-80. PMID: 25689043

- Carlson SM, Moore KE, Sankaran SM, Reynoird N, Elias JE, Gozani O. (2015) A Proteomic Strategy Identifies Lysine Methylation of Splicing Factor snRNP70 by the SETMAR Enzyme. <strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/25795785" target="_blank"> <span style="color: #0000ff;"> J Biol Chem </span></a></strong>. 2015 May 8;290(19):12040-7. PMID: 25795785

**2014:**

- <p style="text-align: justify;">Zhongjun Cheng, Peggie Cheung, Alex J. Kuo, Erik T. Yukl, Carrie M. Wilmot, Or Gozani<sup>#</sup> and Dinshaw J. Patel<sup>#</sup>. (2014) A Molecular Threading Mechanism Underlies Jumonji Lysine Demethylase KDM2A Regulation of Methylated H3K36. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=25128496" target="_blank"> <span style="color: #0000ff;"> <strong>Genes and Development</strong></span></a>, (2014), 15;28(10): 1758-71. PMID: 25128496  #co-correspondence</p>

- <p style="text-align: justify;">Reynoird N, Gozani O. (2014) Nuclear PI5P, Uhrf1, and the Road Not Taken. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=24950375" target="_blank"> <span style="color: #0000ff;"> Molecular Cell</span></a>.</strong></span> 2014 Jun 19;54(6):901-3. PMID: 24950375</p>

- <p style="text-align: justify;">Pawel K. Mazur<strong>*</strong>, Nicolas Reynoird<strong>*</strong>, Purvesh Khatri, Pascal W.T.C. Jansen, Alex Wilkinson, Shichong Liu, Olena Barbash, Glenn S. Van Aller, Michael Huddleston, Dashyant Dhanak, Peter J. Tummino, Ryan G. Kruger, Benjamin Garcia, Atul J. Butte, Michiel Vermeulen, Julien Sage<strong>#</strong>, and <b>Or Gozani</b><strong>#</strong> (2014). SMYD3 links lysine methylation of MAP3K2 to Ras-driven cancer. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=24847881" target="_blank"><span style="color: #0000ff;"><strong>Nature</strong></span></a>, 2014 Jun 12;510(7504):283-7. PMID 24847881 <em><strong>*</strong>These authors contributed equally to this work</em>; <strong>#</strong>Equal correspondence</p>

- <p style="text-align: justify;">Carlson SM, Gozani O. Emerging Technologies to Map the Protein Methylome. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=24805349" target="_blank"><strong><span style="color: #0000ff;">J Mol Biol</span></strong></a>. 2014 May 5. S0022-2836(14). PMID: 24805349</p>

- <p style="text-align: justify;">Moore KE and Gozani O.  An unexpected journey: Lysine methylation across the proteome. 2014. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=24561874" target="_blank"><span style="color: #0000ff;"><strong><span style="color: #0000ff;">B</span>iochim Biophys Acta</strong></span></a>. 2014 Feb 20 S1874-9399(14)00029-7. PMID: 24561874</p>

- <p style="text-align: justify;">Wilkinson A and Gozani O. Histone-binding domains: Strategies for discovery and characterization. 2014. <span style="color: #0000ff;"><strong><a title="BBA publication 2014 with A Wilkinson" href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Wilkinson+A+and+Gozani+O" target="_blank"><span style="color: #0000ff;">Biochim Biophys Act</span></a>a</strong></span>, 2014 S1874-9399(14)00022-4. PID: 24525102</p>

- <p style="text-align: justify;">Martin GM, King DA, Green EM, Garcia-Nieto PE, Alexander R., Collins SR, Krogan NJ, Gozani O, and Morrison AJ.  Set5 and Set1 cooperate to repress gene expression at telomeres and retrotransposons.  2014. <a title="Epigenetics publication 2014" href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Martin+GM%2C+King+DA%2C+Green+EM%2C+Garcia-Nieto+PE" target="_blank"><strong><span style="color: #0000ff;">Epigenetics</span></strong></a>, Jan 17;9(4)</p>

- <p style="text-align: justify;"><span style="color: #000000;">Carlson SM, Moore KE, Green EM, Martin GM, and Gozani O.  Proteome-wide enrichment of proteins modified by lysine methylation.  2014. <a title="Nature Protocol publication 2014" href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Carlson+SM%2C+Moore+KE%2C+Green+EM%2C+Martin+GM" target="_blank"><strong><span style="color: #0000ff;">Nature Protocol</span></strong></a>. Jan;9(1):37-50, doi: 10.1038/nprot.2013.164</span></p>

- <p style="text-align: justify;">Or Gozani and Yang Shi, <span style="text-decoration: underline;">Chapter 5: Histone Methylation in Chromatin Signaling</span>, <em>Fundamentals of Chromatin</em>, edited by Jerry Workman and Susan Abmayr, <span style="color: #0000ff;"><strong>Springer Press</strong></span>, New York (2014)</p>

**2013:**

- <p style="text-align: justify;">Bua DJ, Martin GM, Binda O, and Gozani O.  Nuclear phosphatidylinositol-5-phospate regulates ING2 stability at discrete chromatin targets in response to DNA damage. <a title="Sci Rep publication 2013" href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Bua+DJ%2C+Martin+GM%2C+Binda+O%2C+and+Gozani" target="_blank"><strong><span style="color: #0000ff;">Sci Rep</span></strong></a>. 2013; 3:2137. doi: 10.1038/srep02137</p>

- <p style="text-align: justify;">Moore KE, Carlson SM, Camp ND, Cheung P, James RG, Chua KF, Wolf-Yadlin A, Gozani O. A General Molecular Affinity Strategy for Global Detection and Proteomic Analysis of Lysine Methylation. <strong><span style="color: #0000ff;"><a href="http://www.ncbi.nlm.nih.gov/pubmed/23583077" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Mol Cell</span></a></span></strong>. 2013 Apr 9. doi: pii: S1097-2765(13)00209-8. 10.1016.</p>

- <p style="text-align: justify;">Paul S, Kuo A, Schalch T, Vogel H, Joshua-Tor L, McCombie WR, Gozani O, Hammell M, Mills AA. Chd5 requires PHD-mediated histone 3 binding for tumor suppression. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/23318260" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Cell Rep</span></a></strong></span>. 2013 Jan 31;3(1):92-102. doi: 10.1016/j.celrep.2012.12.009. Epub 2013 Jan 10.</p>

**2012:**

- <p style="text-align: justify;">Ballaré C, Lange M, Lapinaite A, Martin GM, Morey L, Pascual G, Liefke R, Simon B, Shi Y, Gozani O, Carlomagno T, Benitah SA, Di Croce L. Phf19 links methylated Lys36 of histone H3 to regulation of Polycomb activity. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/23104054" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Nat Struct Mol Biol</span></a></strong></span>. 2012 Dec;19(12):1257-65. doi: 10.1038/nsmb.2434. Epub 2012 Oct 28.</p>

- <p style="text-align: justify;">Price JV, Tangsombatvisit S, Xu G, Yu J, Levy D, Baechler EC, Gozani O, Varma M, Utz PJ, Liu CL. On silico peptide microarrays for high-resolution mapping of antibody epitopes and diverse protein-protein interactions. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/22902875" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Nat Med</span></a></strong></span>. 2012 Sep;18(9):1434-40.</p>

- <p style="text-align: justify;" align="justify">Green EM, Gozani O. Everybody's welcome: The big tent approach to epigenetic drug discovery. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/23505394" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Drug Discov Today Ther Strateg</span></a></strong></span>. 2012 Fall;9(2-3):e75-e81. Epub 2011 Sep 20.</p>

- <p style="text-align: justify;" align="justify">Calnan DR, Webb AE, White JL, Stowe TR, Goswami T, Shi X, Espejo A, Bedford MT, Gozani O, Gygi SP, Brunet A. Methylation by Set9 modulates FoxO3 stability and transcriptional activity. <strong><span style="color: #0000ff;"><a href="http://www.ncbi.nlm.nih.gov/pubmed/22820736" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Aging</span></a> </span></strong>(Albany NY). 2012 Jul;4(7):462-79.</p>

- <p style="text-align: justify;" align="justify">Barber MF, Michishita-Kioi E, Xi Y, Tasselli L, Kioi M, Moqtaderi Z, Tennen RI, Paredes S, Young NL, Chen K, Struhl K, Garcia BA, Gozani O, Li W, Chua KF. SIRT7 links H3K18 deacetylation to maintenance of oncogenic transformation. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/22722849" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Nature</span></a></strong></span>. 2012 Jul 5;487(7405):114-8. doi: 10.1038/nature11043.</p>

- <p style="text-align: justify;" align="justify">Green EM, Morrison AJ, Gozani O. New marks on the block: Set5 methylates H4 lysines 5, 8 and 12. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/22688645" target="_blank"><span style="color: #0000ff;">Nucleus</span></a></strong></span>. 2012 Jul 1;3(4):335-9. Epub 2012 Jun 12.</p>

- <p style="text-align: justify;" align="justify">Van Aller GS, Reynoird N, Barbash O, Huddleston M, Liu S, Zmoos AF, McDevitt P, Sinnamon R, Le B, Mas G, Annan R, Sage J, Garcia BA, Tummino PJ, Gozani O, Kruger RG. Smyd3 regulates cancer cell phenotypes and catalyzes histone H4 lysine 5 methylation. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/22419068" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Epigenetics</span></a></strong></span>. 2012 Apr;7(4):340-3. doi: 10.4161/epi.19506. Epub 2012 Apr 1</p>

- <p align="justify">Kuo AJ, Song J, Cheung P, Ishibe-Murakami S, Yamazoe S, Chen JK, Patel DJ, Gozani O.The BAH domain of ORC1 links H4K20me2 to DNA replication licensing and Meier-Gorlin syndrome. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/22398447" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Nature</span></a></strong>.</span> 2012 Mar 7. doi: 10.1038/nature10956.</p>

- <p align="justify">Green EM, Mas G, Young NL, Garcia BA, Gozani O. Methylation of H4 lysines 5, 8 and 12 by yeast Set5 calibrates chromatin stress responses. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/22343720" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Nat Struct Mol Biol</span></a></strong></span>. 2012 Feb 19;19(3):361-3. doi: 10.1038/nsmb.2252.</p>

- <p align="justify">Liu CL, Tangsombatvisit S, Rosenberg JM, Mandelbaum G, Gillespie EC, Gozani OP, Alizadeh AA, Utz PJ. Specific post-translational histone modifications of neutrophil extracellular traps as immunogens and potential targets of lupus autoantibodies. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/22300536" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Arthritis Res Ther</span></a></strong></span>. 2012 Feb 2;14(1):R25.</p>


**2011:**

- <p align="justify">Kuo AJ, Cheung P, Chen K, Zee BM, Kioi M, Lauring J, Xi Y, Park BH, Shi X, Garcia BA, Li W, Gozani O. NSD2 links dimethylation of histone H3 at lysine 36 to oncogenic programming. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/22099308" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Mol Cell</span></a></strong></span>. 2011 Nov 18;44(4):609-20.</p>

- <p align="justify">Levy D, Liu CL, Yang Z, Newman AM, Alizadeh AA, Utz PJ, Gozani O. A proteomic approach for the identification of novel lysine methyltransferase substrates. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/22024134" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Epigenetics Chromatin</span></a></strong></span>. 2011 Oct 24;4:19</p>

- <p align="justify">West LE, Gozani O. Regulation of p53 function by lysine methylation. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/21826189" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Epigenomics</span></a></strong>.</span> 2011 Jun;3(3):361-9</p>

- Lee JS, Kim Y, Bhin J, Shin HJ, Nam HJ, Lee SH, Yoon JB, Binda O, Gozani O, Hwang D, Baek SH . Hypoxia-induced methylation of a pontin chromatin remodeling factor. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/21825155" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Proc Natl Acad Sci U S A</span></a></strong></span>. 2011 Aug 16;108(33):13510-5

- <p align="justify">Green EM, Gozani O. CUL4B: trash talking at chromatin. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/21816341" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Mol Cell</span></a></strong>.</span> 2011 Aug 5;43(3):321-3.</p>

- <p align="justify">Chang Y, Levy D, Horton JR, Peng J, Zhang X, Gozani O, Cheng X. Structural basis of SETD6-mediated regulation of the NF-kB network via methyl-lysine signaling.<span style="color: #0000ff;"><strong> <a href="http://www.ncbi.nlm.nih.gov/pubmed/21515635" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Nucleic Acids Res</span></a></strong></span>. 2011 Aug;39(15):6380-9</p>

- <p align="justify">Dan Levy, Alex J. Kuo, Yanqi Chang, Uwe Schaefer, Christopher Kitson, Peggie Cheung, Alexsandra Espejo, Barry M. Zee, Chih Long Liu, Stephanie Tangsombatvisit, Ruth I. Tennen, Andrew Y. Kuo, Song Tanjing, Regina Cheung, Katrin F. Chua, Paul J. Utz, Xiaobing Shi, Rab K. Prinjha, Kevin Lee, Benjamin A. Garcia, Mark T. Bedford, Alexander Tarakhovsky, Xiaodong Cheng and Or Gozani (2011). Lysine methylation of the NF-κB subunit RelA by SETD6 couples activity of the histone methyltransferase GLP at chromatin to tonic repression of NF-κB signaling. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/21131967" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Nature Immunology</span></a></strong></span>, 12(1):29-36.</p>

- <p align="justify">Olivier Binda, Michael Boyce, Jason S. Rush, Krishnan K. Palaniappan, Carolyn R. Bertozzi, and Or Gozani (2011). A Chemical Method for Labeling Lysine Methyltransferase Substrates. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/21243721" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">ChemBioChem</span></a></strong></span>, doi: 10.1002/cbic.201000433.</p>

**2010:**

- <p align="justify">Tsai WW, Wang Z, Yiu TT, Akdemir KC, Xia W, Winter S, Tsai CY, Shi X, Schwarzer D, Plunkett W, Aronow B, Gozani O, Fischle W, Hung MC, Patel DJ, Barton MC. TRIM24 links a non-canonical histone signature to breast cancer. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/21164480" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Nature</span></a></strong></span>. 2010 Dec 16;468(7326):927-32</p>

- <p align="justify">Lisandra E. West, Siddhartha Roy, Karin Lachmi-Weiner, Ryo Hayashi, Xiaobing Shi, Ettore Appella, Tatiana G. Kutateladze#, and Or Gozani# (2010). The MBT repeats of L3MBTL1 link set8 mediated p53 methylation at lysine 382 to target gene repression. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/20870725" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">J. Biol. Chem</span></a></strong></span>. doi: 10.1074/jbc.M110.139527; # equal correspondence</p>

- <p align="justify">Louis A. Saddic, Lisandra E. West, Aaron Aslanian, John R. Yates, Seth M. Rubin, Or Gozani, and Julien Sage (2010). Methylation of the retinoblastoma tumor suppressor by SMYD2.<span style="color: #0000ff;"><strong> <a href="http://www.ncbi.nlm.nih.gov/pubmed/20870719" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">J. Biol. Chem</span></a></strong></span>. doi: 10.1074/jbc.M110.137612</p>

- <p align="justify">Dan Levy and Or Gozani (2010). Decoding chromatin goes high tech. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/20850007" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Cell</span></a></strong>,</span> 17;142(6):844-6</p>

- <p align="justify">Greer EL, Maures TJ, Hauswirth AG, Green EM, Leeman DS, Maro GS, Han S, Banko MR, Gozani O, Brunet A. (2010) Members of the H3K4 trimethylation complex regulate lifespan in a germline-dependent manner in C. elegans. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/20555324" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Nature</span></a></strong></span>; 466(7304):383-7.</p>

- <p align="justify">Kleine-Kohlbrecher D, Christensen J, Vandamme J, Abarrategui I, Bak M, Tommerup N, Shi X, Gozani O, Rappsilber J, Salcini AE, Helin K (2010). A Functional Link between the Histone Demethylase PHF8 and the Transcription Factor ZNF711 in X-Linked Mental Retardation. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Kleine-Kohlbrecher+D%2C+Christensen+J%2C+Vandamme+J%2C+Abarrategui+I%2C+Bak+M%2C+Tommerup+N%2C+Shi+X%2C+Gozani+O%2C+Rappsilber+J%2C+Salcini+AE%2C+Helin+K+(2010).+A+Functional+Link+between+the+Histone+Demethylase+PHF8+and+the+Transcription+Factor+ZNF711+in+X-Linked+Mental+Retardation.+Molecular+Cell.+23%3B38(2)%3A165-78." target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Molecular Cell</span></a></strong></span>. 23;38(2):165-78.</p>

- <p align="justify">Chang PY, Hom RA, Musselman CA, Zhu L, Kuo A, Gozani O, Kutateladze TG, Cleary ML (2010). Binding of the MLL PHD3 finger to histone H3K4me3 is required for MLL-dependent gene transcription. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Chang+PY%2C+Hom+RA%2C+Musselman+CA%2C+Zhu+L" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;"> J Mol Biol</span></a></strong></span>, 400(2):137-44.</p>

- <p align="justify">Hom RA, Chang PY, Roy S, Musselman CA, Glass KC, Selezneva AI, Gozani O, Ismagilov RF, Cleary ML, Kutateladze TG (2010). Molecular mechanism of MLL PHD3 and RNA recognition by the Cyp33 RRM domain. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Hom+RA%2C+Chang+PY%2C+Roy+S%2C+Musselman+CA" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">J Mol Biol</span></a></strong></span>;400(2):145-54.</p>

- <p align="justify">Lee JS, Kim Y, Kim IS, Kim B, Choi HJ, Lee JM, Shin HJ, Kim JH, Kim JY, Seo SB, Lee H, Binda O, Gozani O, Semenza GL, Kim M, Kim KI, Hwang D, Baek SH (2010). Negative regulation of hypoxic responses via induced Reptin methylation. <span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/20603076" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;">Mol Cell</span></a></strong></span>; 39(1):71-85.</p>

- <p align="justify">Roy S, Musselman CA, Kachirskaia I, Hayashi R, Glass KC, Nix JC, Gozani O, Appella E, Kutateladze TG (2010). Structural insight into p53 recognition by the 53BP1 tandem Tudor domain.<span style="color: #0000ff;"><strong><a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Roy+S%2C+Musselman+CA%2C+Kachirskaia+I%2C+Hayashi+R" target="_blank"><span style="font-family: 'Times New Roman'; font-size: medium; color: #0000ff;"> J Mol Biol</span></a></strong></span>. 14;398(4):489-96.</p>

**2009:**

- <p align="justify">Dennis J. Bua, Alex J. Kuo, Peggie Cheung, Chih Long Liu, Valentina Migliori, Alexsandra Espejo, Fabio Casadio, Christian Bassi, Bruno Amati, Mark T. Bedford, Ernesto Guccione, and Or Gozani. (2009) Epigenome Microarray Platform for Proteome-Wide Dissection of Chromatin-Signaling Networks. <strong><span style="color: #0000ff;">PLoS ONE</span></strong> 4(8): e6789. doi: 10.1371/journal.pone.0006789 [<a href="http://www.stanford.edu/group/gozani/pdf/Bua_Epigenome%20Microarray%20Platform%20for%20Proteome-Wide%20Dissection%20of%20Chromatin-Signaling%20Networks.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Michishita E, McCord RA, Boxer LD, Barber MF, Hong T, Gozani O, Chua KF (2009).  Cell cycle-dependent deacetylation of telomeric histone H3 lysine K56 by human SIRT6. <span style="color: #0000ff;"><strong>Cell Cycle</strong></span>.8(16):2664-6. [<a href="http://www.stanford.edu/group/gozani/pdf/Michishita_Cell%20cycle-dependent%20deacetylation%20of%20telomeric%20histone%20H3%20lysine%20K56%20by%20human%20SIRT6.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Li Y, Trojer P, Xu CF, Cheung P, Kuo A, Drury WJ 3rd, Qiao Q, Neubert TA, Xu RM, Gozani O, Reinberg D (2009). The target of the NSD family of histone lysine methyl transferases depends on the nature of the substrate.  <span style="color: #0000ff;"><strong>J Biol Chem</strong></span>, 284, 34283-34295. [<a href="http://www.stanford.edu/group/gozani/pdf/LI_The%20target%20of%20the%20NSD%20family%20of%20histone%20lysine%20methyl%20transferases%20depends%20on%20the%20nature%20of%20the%20substrate.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">McCord RA, Michishita E, Hong T, Berber E, Boxer LD, Kusumoto R, Guan S, Shi X, Gozani O, Burlingame AL, Bohr VA, and Chua KF (2009).SIRT6 stabilizes DNA-dependent Protein Kinase at chromatin for DNA double-strand break repair. <span style="color: #0000ff;"><strong>Aging </strong></span>1: 109-121. [<a href="http://www.stanford.edu/group/gozani/pdf/McCord_SIRT6%20stabilizes%20DNA-dependent%20Protein%20Kinase%20at%20chromatin%20for%20DNA%20double-strand%20break%20repair.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Nehmé Saksouk, Nikita Avvakumov ,Karen S. Champagne, Tiffany Hung, Yannick Doyon, Christelle Cayrou, Eric Paquet, Mukta Ullah, Anne-Julie Landry, Valérie Côté, Xiang-Jiao Yang, Or Gozani, Tatiana G. Kutateladze and Jacques Côté. (2009) HBO1 HAT Complexes Target Chromatin throughout Gene Coding Regions via Multiple PHD Finger Interactions with Histone H3 Tail.  <span style="color: #0000ff;"><strong>Molecular Cell</strong></span>, 33(2): 257-265. [<a href="http://www.stanford.edu/group/gozani/pdf/Saksouk_HBO1%20HAT%20Complexes%20Target%20Chromatin%20throughout%20Gene%20Coding%20Regions%20via%20Multiple%20PHD%20Finger%20Interactions%20with%20Histone%20H3%20Tail.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Tiffany Hung, Olivier Binda, Karen S. Champagne, Alex J. Kuo, Kyle Johnson, Howard Y. Chang, Matthew D. Simon, Tatiana G. Kutateladze and Or Gozani (2009).  ING4 mediates crosstalk between histone H3K4 trimethylation and H3 acetylation to attenuate cellular transformation.  <span style="color: #0000ff;"><strong>Molecular Cell</strong>,</span> 33(2): 248-256. [<a href="http://www.stanford.edu/group/gozani/pdf/Hung_ING4%20mediates%20crosstalk%20between%20histone%20H3K4%20trimethylation%20and%20H3%20acetylation%20to%20attenuate%20cellular%20transformation.pdf" target="_blank">Full Text PDF</a>]</p>


**2008:**

- <p align="justify">Pedro V. Peña, Catherine A. Musselman, Alex J. Kuo, William P. Schiemann, Or Gozani, and Tatiana G. Kutateladze (2008). NMR assignments and histone specificity of the ING2 PHD.  <span style="color: #0000ff;"><strong>Magnetic Resonance in Chemistry</strong></span>, 47(4): 352-358. [<a href="http://www.stanford.edu/group/gozani/pdf/Pena_NMR%20assignments%20and%20histone%20specificity%20of%20the%20ING2%20PHD.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Koh AS, Kuo AJ, Park SY, Cheung P, Abramson J, Bua D, Carney D, Shoelson SE, Gozani O, Kingston RE, Benoist C, and D. Mathis (2008).  Aire employs a histone-binding module to mediate immunological tolerance, linking chromatin regulation with organ-specific autoimmunity.  <span style="color: #0000ff;"><strong>Proc Natl Acad Sci</strong>,</span> 105(41): 15878-83.[<a href="http://www.stanford.edu/group/gozani/pdf/KOH_Aire%20employs%20a%20histone-binding%20module%20to%20mediate%20immunological%20tolerance,%20linking%20chromatin%20regulation%20with%20organ-specific%20autoimmunity.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Kachirskaia I, Shi X, Yamaguchi H, Tanoue K, Wen H, Wang EW, Appella E, and O. Gozani (2008).  Role for 53BP1 tudor domain recognition of p53 dimethylated at lysine 382 in DNA damage signaling.  <span style="color: #0000ff;"><strong>Journal of Biological Chemistry</strong></span>, 283(50):34660-6.[<a href="http://www.stanford.edu/group/gozani/pdf/Kachirskaia_Role%20for%2053BP1%20tudor%20domain%20recognition%20of%20p53%20dimethylated%20at%20lysine%20382%20in%20DNA%20damage%20signaling.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Peña PV, Hom RA, Hung T, Lin H, Kuo AJ, Wong RP, Subach OM, Champagne KS, Zhao R, Verkhusha VV, Li G, Gozani O, and TG Kutateladze (2008).  Histone H3K4me3 binding is required for the DNA repair and apoptotic activities of ING1 tumor suppressor. <span style="color: #0000ff;"><strong>J Mol Biol</strong></span>, 380(2):303-12. [<a href="http://www.stanford.edu/group/gozani/pdf/Pena_JBC_Histone%20H3K4me3%20binding%20is%20required%20for%20the%20DNA%20repair%20and%20apoptotic%20activities%20of%20ING1%20tumor%20suppressor.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Michishita, E., McCord, R.A., Berber E., Kioi, M., Padilla-Nash, H,, Damian, M., Cheung, P., Kusomoto, R., Kawahara, T.L.A., Barrett, J.C., Chang, H.Y., Bohr, V.A., Ried, T., Gozani, O. and K.F. Chua (2008). SIRT6 is a histone H3 lysine 9 deacetylase that modulates telomeric chromatin. <span style="color: #0000ff;"><strong>Nature</strong></span>, 452(7186):492-6.[<a href="http://www.stanford.edu/group/gozani/pdf/Michishita_SIRT6%20is%20a%20histone%20H3%20lysine%209%20deacetylase%20that%20modulates%20telomeric%20chromatin.pdf" target="_blank">Full Text PDF</a>]</p>


**2007:**

- <p align="justify">Adam G. W. Matthews*, Alex J. Kuo*, Santiago Ramon-Maiques, Sunmi Han, Karen S. Champagne, Dmitri Ivanov, Mercedes Gallardo, Dylan Carney, Peggie Cheung, David N. Ciccone, Kay L. Walter, Paul J. Utz, Yang Shi, Tatiana G. Kutateladze, Wei Yang, Or Gozani# &amp; Marjorie A. Oettinger# (2007). RAG2 PHD finger couples histone H3 lysine 4 trimethylation with V(D)J recombination. <span style="color: #0000ff;"><strong>Nature</strong></span>, 450(7172):1106-10. [<a href="http://www.stanford.edu/group/gozani/pdf/Matthews_RAG2%20PHD%20finger%20couples%20histone%20H3%20lysine%204%20trimethylation%20with%20V%28D%29J%20recombination.pdf" target="_blank">Full Text PDF</a>]
*These authors contributed equally to this work
<strong>#Equal correspondence</strong></p>

- <p align="justify">Santiago Ramon-Maiques, Alex J. Kuo, Dylan Carney, Adam G. W. Matthews, Marjorie A. Oettinger, Or Gozani, and Wei Yang (2007). The PHD finger of RAG2 recognizes histone H3 methylated at both lysine-4 and arginine-2. <span style="color: #0000ff;"><strong>PNAS</strong></span>, 104(48):18993-8. [<a href="http://www.stanford.edu/group/gozani/pdf/Maiques_The%20PHD%20finger%20of%20RAG2%20recognizes%20histone%20H3%20methylated%20at%20both%20lysine-4%20and%20arginine-2.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Shi, X., Kachirskaia, I., Yamaguchi, H., West, L.E., Wen, H., Wang, E.W., Dutta, S., Appella, E. and Or Gozani (2007). Modulation of p53 function by SET8-mediated methylation at lysine 382. <span style="color: #0000ff;"><strong>Molecular Cell</strong></span>, 27: 636-646.[<a href="http://www.stanford.edu/group/gozani/pdf/Shi_Modulation%20of%20p53%20function%20by%20SET8-mediated%20methylation%20at%20lysine%20382.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Huang, W., Zhang, H., Davrazou, F., Kutateladze, T.G., Shi, X., Gozani, O. and G.D. Prestwich (2007). Stabilized Phosphatidylinositol-5-Phosphate Analogues as Ligands for the Nuclear Protein ING2: Chemistry, Biology and Molecular Modeling.  <strong><span style="color: #0000ff;">JACS</span> </strong>129(20):6498-506.[<a href="http://www.stanford.edu/group/gozani/pdf/Huang_Stabilized%20Phosphatidylinositol-5-Phosphate%20Analogues%20as%20Ligands%20for%20the%20Nuclear%20Protein%20ING2%20Chemistry%20Biology%20and%20Molecular%20Modeling.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Shi, X., Kachirskaia, I., Walter K.L., Kuo, J.H., Lake A., Davrazou, F., Chan, S.M., Martin, D.G., Fingerman, I.M., Briggs, S.D., Howe, L., Utz, P.J., Kutateladze, T.G., Lugovskoy, A.A., Bedford, M.T., and O. Gozani(2007). Proteome-wide analysis in S. cerevisae identifies several PHD fingers as novel direct and selective binding modules of histone H3 methylated at either lysine 4 or lysine 36. <span style="color: #0000ff;"><strong>JBC</strong></span>, 282, 2450-2455.[<a href="http://www.stanford.edu/group/gozani/pdf/Shi_Proteome-wide%20analysis%20in%20S.%20cerevisae%20identifies%20several%20PHD%20fingers%20as%20novel%20direct%20and%20selective%20binding%20modules%20of%20histone%20H3%20methylated%20at%20either%20lysine%204%20or%20lysine%2036.pdf" target="_blank">Full Text PDF</a>]</p>

**2006:**

- <p align="justify">David G. E. Martin, Kristin Baetz, Xiaobing Shi, Kay L. Walter, Vicki E. MacDonald, Martin J. Wlodarski, Or Gozani, Philip Hieter, and LeAnn Howe (2006). The Yng1p Plant Homeodomain Finger Is a Methyl-Histone Binding Module That Recognizes Lysine 4-Methylated Histone H3. <span style="color: #0000ff;"><strong>MCB</strong></span>, 26: 7871-7879.[<a href="http://www.stanford.edu/group/gozani/pdf/Martin_The%20Yng1p%20Plant%20Homeodomain%20Finger%20Is%20a%20Methyl-Histone%20Binding%20Module%20That%20Recognizes%20Lysine%204-Methylated%20Histone%20H3.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Xiaobing Shi, Tao Hong, Kay L. Walter, Mark Ewalt, Eriko Michishita, Tiffany Hung, Dylan Carney, Pedro Peña, Fei Lan, Mohan R. Kaadige, Nicolas Lacoste, Christelle Cayrou Foteini Davrazou, Anjanabha Saha, Bradley R. Cairns, Donald E. Ayer, Tatiana G. Kutateladze, Yang Shi, Jacques Côté, Katrin F. Chua, and Or Gozani (2006). ING2 PHD domain links histone H3 lysine 4 methylation to active gene repression. <span style="color: #0000ff;"><strong>Nature</strong></span>, 442, 96-99. [<a href="http://www.stanford.edu/group/gozani/pdf/Shi_ING2%20PHD%20domain%20links%20histone%20H3%20lysine%204%20methylation%20to%20active%20gene%20repression.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Pedro V. Peña, Foteini Davrazou, Xiaobing Shi, Kay L. Walter, Vladislav V. Verkhusha, Or Gozani, Rui Zhao and Tatiana G. Kutateladze (2006). Molecular mechanism of histone H3K4me3 recognition by plant homeodomain of ING2.  <strong><span style="color: #0000ff;">Nature</span></strong>, 442, 100-103. [<a href="http://www.stanford.edu/group/gozani/pdf/Pena_Molecular%20mechanism%20of%20histone%20H3K4me3%20recognition%20by%20plant%20homeodomain%20of%20ING2.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Caroline Pendaries, Hélène Tronchère, Laurence Arbibe, Joelle Mounier, Or Gozani, Lewis Cantley, Michael J Fry, Frédérique Gaits-Iacovoni, Philippe J Sansonetti and Bernard Payrastre (2006).  PtdIns(5)P activates the host cell PI3-kinase/Akt pathway during Shigella flexneri infection.  <strong><span style="color: #0000ff;">The EMBO Journal</span></strong>,  25: 1024-1034.[<a href="http://www.stanford.edu/group/gozani/pdf/PtdIns%285%29P%20activates%20the%20host%20cell%20PI3-kinase-Akt.pdf" target="_blank">Full Text PDF</a>]</p>


**2005:**

- <p align="justify">Xiaobing Shi and Or Gozani (2005). The Fellowships of the INGs.  <span style="color: #0000ff;"><strong>Journal of Cellular Biochemistry</strong></span>, 96(6): 1127-1136.[<a href="http://www.stanford.edu/group/gozani/pdf/fellowship%20of%20ings.pdf" target="_blank">Full Text PDF</a>]</p>

- <p align="justify">Sheryl K. Elkin, Dmitri Ivanov, Mark Ewalt, Colin G. Ferguson, Sven G. Hyberts, Zhen-Yu J. Sun, Glenn D. Prestwich, Junying Yuan, Gerhard Wagner, Marjorie A. Oettinger, Or Gozani (2005). A PHD finger motif in the C-terminus of RAG2 modulates recombination activity. <strong><span style="color: #0000ff;">JBC</span></strong>, 280(31): 28701-10.[<a href="http://www.stanford.edu/group/gozani/pdf/Elkin_A%20PHD%20finger%20motif%20in%20the%20C-terminus%20of%20RAG2%20modulates%20recombination%20activity.pdf" target="_blank">Full Text PDF</a>]</p>
